"""媒体领域模块导出。"""

from .compose import (
    DEFAULT_DUB_AUDIO_LEVELING_ACTIVITY_THRESHOLD_DB,
    DEFAULT_DUB_AUDIO_LEVELING_MAX_GAIN_DB,
    DEFAULT_DUB_AUDIO_LEVELING_PEAK_CEILING,
    DEFAULT_DUB_AUDIO_LEVELING_TARGET_RMS,
    build_dubbed_video_two_step,
    build_full_timeline_bgm,
    build_full_timeline_mix,
    build_full_timeline_vocals,
    compose_vocals_master,
    concat_generated_wavs,
    concat_wav_files,
    has_video_stream,
    merge_bilingual_srt_files,
    merge_srt_files,
    mix_vocals_with_bgm,
    mix_with_bgm,
    normalize_speech_audio_level,
    prepare_dubbed_audio_for_video,
    replace_video_audio_two_step,
)
from .probe import audio_duration, ffprobe_duration, load_mono_audio, resample_mono_audio
from .segment import (
    choose_boundaries,
    cut_audio_segment,
    detect_silence_endpoints,
    detect_speech_time_ranges,
    extract_source_audio,
    map_global_ranges_to_segment,
    normalize_time_ranges,
)

__all__ = [
    "audio_duration",
    "ffprobe_duration",
    "load_mono_audio",
    "resample_mono_audio",
    "choose_boundaries",
    "cut_audio_segment",
    "detect_silence_endpoints",
    "detect_speech_time_ranges",
    "extract_source_audio",
    "map_global_ranges_to_segment",
    "normalize_time_ranges",
    "DEFAULT_DUB_AUDIO_LEVELING_ACTIVITY_THRESHOLD_DB",
    "DEFAULT_DUB_AUDIO_LEVELING_MAX_GAIN_DB",
    "DEFAULT_DUB_AUDIO_LEVELING_PEAK_CEILING",
    "DEFAULT_DUB_AUDIO_LEVELING_TARGET_RMS",
    "build_dubbed_video_two_step",
    "build_full_timeline_bgm",
    "build_full_timeline_mix",
    "build_full_timeline_vocals",
    "compose_vocals_master",
    "concat_generated_wavs",
    "concat_wav_files",
    "has_video_stream",
    "merge_bilingual_srt_files",
    "merge_srt_files",
    "mix_vocals_with_bgm",
    "mix_with_bgm",
    "normalize_speech_audio_level",
    "prepare_dubbed_audio_for_video",
    "replace_video_audio_two_step",
]
